src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'string', length: 255)]
    private $illustration;

    #[ORM\Column(type: 'string', length: 255)]
    private $subtitle;

    #[ORM\Column(type: 'text')]
    private $Description;

    #[ORM\Column(type: 'integer')]
    private $Price;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }



    #[Route('/nos-produits', name: 'products')]
    public function index(): Response
    {

        $products = $this->entityManager->getRepository(Product::class)->findAll();
            

        return $this->render('product/index.html.twig',[
            'products'=> $products
        ]);
    }


    #[Route('/produit/{slug}', name: 'product')]
    public function show($slug): Response
    {
         
        $product = $this->entityManager->getRepository(Product::class)->findOneBy(['slug'=>$slug]);
            
        if(!$product)
            {
                return $this->redirectToRoute('products');
            }

        return $this->render('product/show.html.twig',[
            'product'=> $product
        ]);
    }
}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos produits La Boutique!{% endblock %}

{% block content %}
        <h1>Nos produits</h1>

        <div class="row">
                {% for product in products %}
                    <div class="col-md-4">
                    <div class="product-item text-center">
                      <a href="{{path('product',{'slug' : product.slug})}}"> <img src="/uploads/{{product.illustration}}" alt="{{product.name}}" class="img-fluid"></a>
                        <h5>{{product.name}}</5>
                        <span>{{product.subtitle}}</span>
                        <br> €{{product.price /100}}
                    </div>
                    </div>
                    
                {% endfor %}
        </div>
       
        
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{product.name}} - La Boutique!{% endblock %}

{% block content %}
        <h1>{{product.name}}</h1>

           <div class="row">

           <div class="col-md-4">
              <img src="/uploads/{{product.illustration}}" alt="{{product.name}}" class="img-fluid">
             </div>

                <div class="col-md-8">
                       <h5>{{product.name}}</h5>
                        <h6><span>{{product.subtitle}}</span></h6>
                        <p>{{product.description}}</p>
                        <br> €{{product.price /100}}<br>
                        <div class="mt-2"><a href="" class="btn btn-primary">Ajouter au panier</a></div>
                    </div>
                    </div>
                    
       
        </div>
       
       
        
{% endblock %}